Repository aws-controllers-k8s/sagemaker-controller, pull requests merged in 2021-07, with the labels that each got.

#53 fix to reduce test flakiness
  test/e2e/__init__.py
  test/e2e/common/fixtures.py
  test/e2e/requirements.txt
  test/e2e/service_bootstrap.py
  test/e2e/tests/test_adopt_endpoint.py
  test/e2e/tests/test_endpoint.py
  test/e2e/tests/test_endpoint_config.py
  test/e2e/tests/test_hpo.py
  test/e2e/tests/test_model_bias_job_definition.py
  test/e2e/tests/test_model_explainability_job_definition.py
  test/e2e/tests/test_model_quality_job_definition.py
  test/e2e/tests/test_monitoring_schedule.py
  test/e2e/tests/test_processingjob.py
  test/e2e/tests/test_trainingjob.py
  test/e2e/tests/test_trainingjob_debugger.py
  test/e2e/tests/test_transformjob.py
Labels: approved, lgtm

#50 Feature group testing
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/enums.go
  apis/v1alpha1/feature_group.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/sagemaker.services.k8s.aws_featuregroups.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  pkg/resource/feature_group/custom_delta.go
  pkg/resource/feature_group/delta.go
  pkg/resource/feature_group/descriptor.go
  pkg/resource/feature_group/identifiers.go
  pkg/resource/feature_group/manager.go
  pkg/resource/feature_group/manager_factory.go
  pkg/resource/feature_group/resource.go
  pkg/resource/feature_group/sdk.go
  test/canary/scripts/run_test.sh
  test/e2e/resources/feature_group.yaml
  test/e2e/tests/test_feature_group.py
Labels: approved, lgtm, ok-to-test

#49 Add infinite requeue to endpoint, monitoring schedule
  apis/v1alpha1/ack-generate-metadata.yaml
  config/crd/common/bases/services.k8s.aws_adoptedresources.yaml
  generator.yaml
  go.mod
  go.sum
  pkg/resource/data_quality_job_definition/manager.go
  pkg/resource/data_quality_job_definition/manager_factory.go
  pkg/resource/data_quality_job_definition/resource.go
  pkg/resource/data_quality_job_definition/sdk.go
  pkg/resource/endpoint/manager.go
  pkg/resource/endpoint/manager_factory.go
  pkg/resource/endpoint/resource.go
  pkg/resource/endpoint/sdk.go
  pkg/resource/endpoint_config/manager.go
  pkg/resource/endpoint_config/manager_factory.go
  pkg/resource/endpoint_config/resource.go
  pkg/resource/endpoint_config/sdk.go
  pkg/resource/hyper_parameter_tuning_job/manager.go
  pkg/resource/hyper_parameter_tuning_job/manager_factory.go
  pkg/resource/hyper_parameter_tuning_job/resource.go
  pkg/resource/hyper_parameter_tuning_job/sdk.go
  pkg/resource/model/manager.go
  pkg/resource/model/manager_factory.go
  pkg/resource/model/resource.go
  pkg/resource/model/sdk.go
  pkg/resource/model_bias_job_definition/manager.go
  pkg/resource/model_bias_job_definition/manager_factory.go
  pkg/resource/model_bias_job_definition/resource.go
  pkg/resource/model_bias_job_definition/sdk.go
  pkg/resource/model_explainability_job_definition/manager.go
  pkg/resource/model_explainability_job_definition/manager_factory.go
  pkg/resource/model_explainability_job_definition/resource.go
  pkg/resource/model_explainability_job_definition/sdk.go
  pkg/resource/model_quality_job_definition/manager.go
  pkg/resource/model_quality_job_definition/manager_factory.go
  pkg/resource/model_quality_job_definition/resource.go
  pkg/resource/model_quality_job_definition/sdk.go
  pkg/resource/monitoring_schedule/manager.go
  pkg/resource/monitoring_schedule/manager_factory.go
  pkg/resource/monitoring_schedule/resource.go
  pkg/resource/monitoring_schedule/sdk.go
  pkg/resource/processing_job/manager.go
  pkg/resource/processing_job/manager_factory.go
  pkg/resource/processing_job/resource.go
  pkg/resource/processing_job/sdk.go
  pkg/resource/training_job/manager.go
  pkg/resource/training_job/manager_factory.go
  pkg/resource/training_job/resource.go
  pkg/resource/training_job/sdk.go
  pkg/resource/transform_job/manager.go
  pkg/resource/transform_job/manager_factory.go
  pkg/resource/transform_job/resource.go
  pkg/resource/transform_job/sdk.go
Labels: approved, lgtm

#46 Feature group sample
  samples/feature_group/README.md
  samples/feature_group/data_ingestion.py
  samples/feature_group/my-feature-group.yaml
  samples/feature_group/my-sample-data.csv
Labels: approved, lgtm, needs-ok-to-test

#48 Add modelpackagegroup crd and e2e test for create/delete
  CODEOWNERS
  OWNERS_ALIASES
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/enums.go
  apis/v1alpha1/model_package_group.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/sagemaker.services.k8s.aws_modelpackagegroups.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  pkg/resource/model_package_group/delta.go
  pkg/resource/model_package_group/descriptor.go
  pkg/resource/model_package_group/hooks.go
  pkg/resource/model_package_group/identifiers.go
  pkg/resource/model_package_group/manager.go
  pkg/resource/model_package_group/manager_factory.go
  pkg/resource/model_package_group/resource.go
  pkg/resource/model_package_group/sdk.go
  templates/common/sdk_delete_post_request.go.tpl
  templates/common/sdk_delete_pre_build_request.go.tpl
  test/canary/scripts/run_test.sh
  test/e2e/requirements.txt
  test/e2e/resources/xgboost_model_package_group.yaml
  test/e2e/tests/test_model_package_group.py
Labels: approved, lgtm

#58 Add service metadata file
  metadata.yaml
Labels: approved, lgtm

#59 Add reduced test flakiness to Canary
  test/e2e/__init__.py
  test/e2e/tests/test_adopt_endpoint.py
Labels: approved, lgtm

#63 Temp remove flaky test
  test/e2e/tests/test_adopt_endpoint.py
Labels: approved, lgtm

#54 Model package e2e
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/enums.go
  apis/v1alpha1/model_package.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/sagemaker.services.k8s.aws_modelpackages.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  pkg/resource/model_package/custom_delta.go
  pkg/resource/model_package/delta.go
  pkg/resource/model_package/descriptor.go
  pkg/resource/model_package/hooks.go
  pkg/resource/model_package/identifiers.go
  pkg/resource/model_package/manager.go
  pkg/resource/model_package/manager_factory.go
  pkg/resource/model_package/resource.go
  pkg/resource/model_package/sdk.go
  pkg/resource/model_package_group/sdk.go
  samples/model_package/README.MD
  samples/model_package/my-model-package.yaml
  samples/model_package_group/README.MD
  samples/model_package_group/my-model-package-group.yaml
  templates/model_package/sdk_update_pre_build_request.go.tpl
  templates/model_package/set_resource_name_as_arn.go.tpl
  test/e2e/common/config.py
  test/e2e/resources/xgboost_model_package_group.yaml
  test/e2e/resources/xgboost_unversioned_model_package.yaml
  test/e2e/resources/xgboost_versioned_model_package.yaml
  test/e2e/tests/test_model_package.py
  test/e2e/tests/test_model_package_group.py
Labels: approved, lgtm

#64 test changes logging debug -> error
  test/canary/scripts/run_test.sh
  test/e2e/common/fixtures.py
  test/e2e/tests/test_adopt_endpoint.py
  test/e2e/tests/test_endpoint.py
  test/e2e/tests/test_endpoint_config.py
  test/e2e/tests/test_feature_group.py
  test/e2e/tests/test_hpo.py
  test/e2e/tests/test_processingjob.py
  test/e2e/tests/test_trainingjob.py
  test/e2e/tests/test_trainingjob_debugger.py
  test/e2e/tests/test_transformjob.py
Labels: approved, lgtm

#65 Add terminal state for failed in modelpackage
  apis/v1alpha1/ack-generate-metadata.yaml
  generator.yaml
  pkg/resource/model_package/custom_update_conditions.go
  pkg/resource/model_package/sdk.go
Labels: approved, lgtm

#67 release artifacts for release v0.0.2
  helm/Chart.yaml
  helm/crds/sagemaker.services.k8s.aws_dataqualityjobdefinitions.yaml
  helm/crds/sagemaker.services.k8s.aws_endpointconfigs.yaml
  helm/crds/sagemaker.services.k8s.aws_endpoints.yaml
  helm/crds/sagemaker.services.k8s.aws_featuregroups.yaml
  helm/crds/sagemaker.services.k8s.aws_hyperparametertuningjobs.yaml
  helm/crds/sagemaker.services.k8s.aws_modelbiasjobdefinitions.yaml
  helm/crds/sagemaker.services.k8s.aws_modelexplainabilityjobdefinitions.yaml
  helm/crds/sagemaker.services.k8s.aws_modelpackagegroups.yaml
  helm/crds/sagemaker.services.k8s.aws_modelpackages.yaml
  helm/crds/sagemaker.services.k8s.aws_modelqualityjobdefinitions.yaml
  helm/crds/sagemaker.services.k8s.aws_models.yaml
  helm/crds/sagemaker.services.k8s.aws_monitoringschedules.yaml
  helm/crds/sagemaker.services.k8s.aws_processingjobs.yaml
  helm/crds/sagemaker.services.k8s.aws_trainingjobs.yaml
  helm/crds/sagemaker.services.k8s.aws_transformjobs.yaml
  helm/crds/services.k8s.aws_adoptedresources.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/metrics-service.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  helm/values.yaml
Labels: approved, lgtm, ok-to-test

#69 bug fixes for v0.0.2 release
  README.md
  helm/templates/cluster-role-binding.yaml
  helm/values.yaml
Labels: approved, lgtm

#70 fix readme
  README.md
Labels: approved, lgtm

#71 Test fixes for ModelPackage and move check for tags once resource completed
  test/canary/scripts/install_controller_helm.sh
  test/e2e/common/config.py
  test/e2e/tests/test_endpoint.py
  test/e2e/tests/test_hpo.py
  test/e2e/tests/test_model_package.py
  test/e2e/tests/test_model_package_group.py
  test/e2e/tests/test_monitoring_schedule.py
  test/e2e/tests/test_processingjob.py
  test/e2e/tests/test_trainingjob.py
  test/e2e/tests/test_trainingjob_debugger.py
Labels: approved, lgtm

#74 release artifacts for release v0.0.3
  README.md
  helm/Chart.yaml
  helm/values.yaml
Labels: approved, lgtm
