Repository aws-controllers-k8s/sagemaker-controller, pull requests merged in 2021-05, with the labels that each got.

#33 Add samples for each CRD
  samples/README.md
  samples/batch_transform/README.md
  samples/batch_transform/my-batch-transform-job.yaml
  samples/endpoint/README.md
  samples/endpoint/endpoint_base.yaml
  samples/endpoint/endpoint_config.yaml
  samples/hyperparameter_tuning/README.md
  samples/hyperparameter_tuning/my-hyperparameter-job.yaml
  samples/job_definitions/data_quality/README.md
  samples/job_definitions/data_quality/my-data-quality-job-definition.yaml
  samples/job_definitions/model_bias/README.md
  samples/job_definitions/model_bias/my-model-bias-job-definition.yaml
  samples/job_definitions/model_explainability/README.md
  samples/job_definitions/model_explainability/my-model-explainability-job-definition.yaml
  samples/job_definitions/model_quality/README.md
  samples/job_definitions/model_quality/my-model-quality-job.yaml
  samples/model/README.md
  samples/model/my-model.yaml
  samples/monitoring_schedule/README.md
  samples/monitoring_schedule/my-monitoring-schedule.yaml
  samples/processing/README.md
  samples/processing/kmeans_preprocessing.py
  samples/processing/my-processing-job.yaml
  samples/training/README.md
  samples/training/my-training-job.yaml
Labels: approved, ok-to-test

#35 docs: installation, CARM, CRM and adopted resource
  README.md
  samples/README.md
  samples/batch_transform/README.md
  samples/endpoint/README.md
  samples/hyperparameter_tuning/README.md
  samples/job_definitions/data_quality/README.md
  samples/job_definitions/model_bias/README.md
  samples/job_definitions/model_explainability/README.md
  samples/job_definitions/model_quality/README.md
  samples/model/README.md
  samples/monitoring_schedule/README.md
  samples/processing/README.md
  samples/training/README.md
Labels: approved

#37 set server defaults for HPO
  generator.yaml
  go.mod
  go.sum
  pkg/resource/hyper_parameter_tuning_job/custom_delta.go
  pkg/resource/hyper_parameter_tuning_job/delta.go
Labels: approved

#36 Add default values to the comparison checker
  generator.yaml
  pkg/resource/model/custom_delta.go
  pkg/resource/model/delta.go
  pkg/resource/processing_job/custom_delta.go
  pkg/resource/processing_job/delta.go
  pkg/resource/training_job/custom_delta.go
  pkg/resource/training_job/delta.go
  pkg/resource/transform_job/custom_delta.go
  pkg/resource/transform_job/delta.go
Labels: approved

#39 Helm install updates, fix PR build
  README.md
  samples/README.md
  test/canary/scripts/install_controller_helm.sh
  test/e2e/service_bootstrap.py
Labels: approved, lgtm

#38 Python script to upload sample data to S3
  samples/README.md
  samples/batch_transform/README.md
  samples/endpoint/README.md
  samples/hyperparameter_tuning/README.md
  samples/hyperparameter_tuning/my-hyperparameter-job.yaml
  samples/job_definitions/data_quality/README.md
  samples/job_definitions/model_bias/README.md
  samples/job_definitions/model_explainability/README.md
  samples/job_definitions/model_quality/README.md
  samples/model/README.md
  samples/monitoring_schedule/README.md
  samples/processing/README.md
  samples/training/README.md
  samples/training/my-training-job.yaml
  samples/training/s3_sample_data.py
Labels: approved, lgtm, needs-ok-to-test

#40 release artifacts for release v0.0.1
  helm/Chart.yaml
  helm/crds/sagemaker.services.k8s.aws_dataqualityjobdefinitions.yaml
  helm/crds/sagemaker.services.k8s.aws_endpointconfigs.yaml
  helm/crds/sagemaker.services.k8s.aws_endpoints.yaml
  helm/crds/sagemaker.services.k8s.aws_hyperparametertuningjobs.yaml
  helm/crds/sagemaker.services.k8s.aws_modelbiasjobdefinitions.yaml
  helm/crds/sagemaker.services.k8s.aws_modelexplainabilityjobdefinitions.yaml
  helm/crds/sagemaker.services.k8s.aws_modelqualityjobdefinitions.yaml
  helm/crds/sagemaker.services.k8s.aws_models.yaml
  helm/crds/sagemaker.services.k8s.aws_monitoringschedules.yaml
  helm/crds/sagemaker.services.k8s.aws_processingjobs.yaml
  helm/crds/sagemaker.services.k8s.aws_trainingjobs.yaml
  helm/crds/sagemaker.services.k8s.aws_transformjobs.yaml
  helm/crds/services.k8s.aws_adoptedresources.yaml
  helm/templates/_helpers.tpl
  helm/templates/cluster-role-binding.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/deployment.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  helm/templates/service-account.yaml
  helm/values.yaml
Labels: approved, lgtm

#41 update runtime to tagged version
  go.mod
  go.sum
Labels: approved, lgtm
