Repository aws-controllers-k8s/sagemaker-controller, pull requests merged in 2021-08, with the labels that each got.

#66 Unit Testing Framework w/ Feature Group sample
  ATTRIBUTION.md
  Makefile
  go.mod
  go.sum
  pkg/resource/feature_group/manager_test_suite_test.go
  pkg/resource/feature_group/testdata/feature_group/v1alpha1/fg_invalid_before_create.yaml
  pkg/resource/feature_group/testdata/feature_group/v1alpha1/fg_invalid_create_attempted.yaml
  pkg/resource/feature_group/testdata/test_suite.yaml
  pkg/testutil/test_suite_config.go
  pkg/testutil/test_suite_runner.go
  pkg/testutil/util.go
  test/mocks/aws-sdk-go/sagemaker/SageMakerAPI.go
  test/scripts/install-mockery.sh
Labels: ok-to-test, approved, lgtm

#68 [Feature Group] Unit Testing
  pkg/resource/feature_group/manager_test_suite_test.go
  pkg/resource/feature_group/testdata/feature_group/create/fg_before_create.json
  pkg/resource/feature_group/testdata/feature_group/read_one/fg_create_failed.json
  pkg/resource/feature_group/testdata/feature_group/read_one/fg_created.json
  pkg/resource/feature_group/testdata/feature_group/read_one/fg_creating.json
  pkg/resource/feature_group/testdata/feature_group/read_one/fg_deleting.json
  pkg/resource/feature_group/testdata/feature_group/v1alpha1/fg_before_create.yaml
  pkg/resource/feature_group/testdata/feature_group/v1alpha1/fg_create_failed_state.yaml
  pkg/resource/feature_group/testdata/feature_group/v1alpha1/fg_create_initiated.yaml
  pkg/resource/feature_group/testdata/feature_group/v1alpha1/fg_created_state.yaml
  pkg/resource/feature_group/testdata/feature_group/v1alpha1/fg_creating_state.yaml
  pkg/resource/feature_group/testdata/feature_group/v1alpha1/fg_deleting_state.yaml
  pkg/resource/feature_group/testdata/test_suite.yaml
  pkg/testutil/test_suite_config.go
  pkg/testutil/test_suite_runner.go
Labels: ok-to-test, approved, lgtm

#78 Remove dockerhub login step and use ECR public gallery ubuntu image
  test/canary/Dockerfile.canary
  test/canary/canary.buildspec.yaml
Labels: approved, lgtm

#79 run go fmt on unit test commit
  apis/v1alpha1/ack-generate-metadata.yaml
  pkg/resource/data_quality_job_definition/manager_test_suite_test.go
  pkg/resource/endpoint/manager_test_suite_test.go
  pkg/resource/endpoint_config/manager_test_suite_test.go
  pkg/resource/feature_group/manager_test_suite_test.go
  pkg/resource/hyper_parameter_tuning_job/manager_test_suite_test.go
  pkg/resource/model/manager_test_suite_test.go
  pkg/resource/model_bias_job_definition/manager_test_suite_test.go
  pkg/resource/model_explainability_job_definition/manager_test_suite_test.go
  pkg/resource/model_package/manager_test_suite_test.go
  pkg/resource/model_package_group/manager_test_suite_test.go
  pkg/resource/model_quality_job_definition/manager_test_suite_test.go
  pkg/resource/monitoring_schedule/manager_test_suite_test.go
  pkg/resource/processing_job/manager_test_suite_test.go
  pkg/resource/training_job/manager_test_suite_test.go
  pkg/resource/transform_job/manager_test_suite_test.go
  pkg/testutil/test_suite_runner.go
  pkg/testutil/util.go
Labels: approved, lgtm

#56 Notebook Instance (Create/Delete) test
  apis/v1alpha1/enums.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/notebook_instance.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/sagemaker.services.k8s.aws_notebookinstances.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  pkg/resource/notebook_instance/custom_sdk_api.go
  pkg/resource/notebook_instance/custom_set_delta.go
  pkg/resource/notebook_instance/delta.go
  pkg/resource/notebook_instance/descriptor.go
  pkg/resource/notebook_instance/hooks.go
  pkg/resource/notebook_instance/identifiers.go
  pkg/resource/notebook_instance/manager.go
  pkg/resource/notebook_instance/manager_factory.go
  pkg/resource/notebook_instance/resource.go
  pkg/resource/notebook_instance/sdk.go
  templates/notebook_instance/sdk_delete_pre_build_request.go.tpl
  test/e2e/resources/notebook_instance.yaml
  test/e2e/tests/test_notebook_instance.py
Labels: ok-to-test, approved, lgtm

#77 Training profiler support
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/training_job.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/sagemaker.services.k8s.aws_trainingjobs.yaml
  generator.yaml
  pkg/resource/training_job/custom_set_output.go
  pkg/resource/training_job/sdk.go
  test/e2e/__init__.py
  test/e2e/common/config.py
  test/e2e/resources/xgboost_trainingjob_debugger.yaml
  test/e2e/tests/test_trainingjob.py
  test/e2e/tests/test_trainingjob_debugger.py
Labels: approved, lgtm

#75 Notebook Instance Lifecycle Configuration Code + Integration test
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/notebook_instance_lifecycle_config.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/sagemaker.services.k8s.aws_notebookinstancelifecycleconfigs.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/Chart.yaml
  helm/crds/sagemaker.services.k8s.aws_notebookinstancelifecycleconfigs.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  helm/values.yaml
  pkg/resource/notebook_instance_lifecycle_config/custom_delta.go
  pkg/resource/notebook_instance_lifecycle_config/delta.go
  pkg/resource/notebook_instance_lifecycle_config/descriptor.go
  pkg/resource/notebook_instance_lifecycle_config/hooks.go
  pkg/resource/notebook_instance_lifecycle_config/identifiers.go
  pkg/resource/notebook_instance_lifecycle_config/manager.go
  pkg/resource/notebook_instance_lifecycle_config/manager_factory.go
  pkg/resource/notebook_instance_lifecycle_config/resource.go
  pkg/resource/notebook_instance_lifecycle_config/sdk.go
  templates/notebook_instance_lifecycle_config/delta_post_compare.go.tpl
  templates/notebook_instance_lifecycle_config/sdk_update_post_set_output.go.tpl
  test/e2e/resources/notebook_instance_lifecycle_config.yaml
  test/e2e/tests/test_notebook_instance_lifecycle.py
Labels: ok-to-test, approved, lgtm

#87 Implement per region instance type config for canary and e2e tests
  test/canary/Dockerfile.canary
  test/e2e/replacement_values.py
  test/e2e/resources/endpoint_config_data_capture_single_variant.yaml
  test/e2e/resources/endpoint_config_multi_variant.yaml
  test/e2e/resources/endpoint_config_single_variant.yaml
  test/e2e/resources/xgboost_trainingjob.yaml
  test/e2e/resources/xgboost_trainingjob_debugger.yaml
Labels: approved, needs-ok-to-test, lgtm

#88 requeue until Stopped for job style resources
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/hyper_parameter_tuning_job/custom_set_output.go
  pkg/resource/hyper_parameter_tuning_job/hooks.go
  pkg/resource/hyper_parameter_tuning_job/sdk.go
  pkg/resource/processing_job/custom_set_output.go
  pkg/resource/processing_job/hooks.go
  pkg/resource/processing_job/sdk.go
  pkg/resource/training_job/hooks.go
  pkg/resource/training_job/sdk.go
  pkg/resource/transform_job/custom_set_output.go
  pkg/resource/transform_job/hooks.go
  pkg/resource/transform_job/sdk.go
  templates/endpoint/sdk_update_pre_build_request.go.tpl
  templates/hyper_parameter_tuning_job/sdk_delete_pre_build_request.go.tpl
  templates/processing_job/sdk_delete_pre_build_request.go.tpl
  templates/training_job/sdk_delete_pre_build_request.go.tpl
  templates/transform_job/sdk_delete_pre_build_request.go.tpl
  test/e2e/common/config.py
  test/e2e/tests/test_hpo.py
  test/e2e/tests/test_processingjob.py
  test/e2e/tests/test_trainingjob.py
  test/e2e/tests/test_trainingjob_debugger.py
  test/e2e/tests/test_transformjob.py
Labels: approved, lgtm

#85 Use tmp file in unit-tests to allow for testing portability
  pkg/testutil/util.go
Labels: approved, lgtm

#89 terminal codes clean up
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/data_quality_job_definition/sdk.go
  pkg/resource/endpoint/sdk.go
  pkg/resource/endpoint_config/sdk.go
  pkg/resource/feature_group/sdk.go
  pkg/resource/model/sdk.go
  pkg/resource/model_bias_job_definition/sdk.go
  pkg/resource/model_explainability_job_definition/sdk.go
  pkg/resource/model_package/sdk.go
  pkg/resource/model_package_group/sdk.go
  pkg/resource/model_quality_job_definition/sdk.go
  pkg/resource/monitoring_schedule/sdk.go
  pkg/resource/notebook_instance/sdk.go
  pkg/resource/notebook_instance_lifecycle_config/sdk.go
Labels: approved, lgtm
