Repository aws-controllers-k8s/sagemaker-controller, pull requests merged in 2021-06, with the labels that each got.

#42 Add python script to upload sample model to S3
  samples/model/README.md
  samples/model/my-model.yaml
  samples/model/s3_sample_model.py
Labels: approved, lgtm, ok-to-test

#43 Update test data bucket
  test/e2e/bootstrap_resources.py
Labels: approved, lgtm, ok-to-test

#44 Update `generator.yaml` print configurations
  generator.yaml
Labels: approved, lgtm

#47 Update documentation and adds logging improved by code-gen changes
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/data_quality_job_definition.go
  apis/v1alpha1/endpoint.go
  apis/v1alpha1/endpoint_config.go
  apis/v1alpha1/hyper_parameter_tuning_job.go
  apis/v1alpha1/model.go
  apis/v1alpha1/model_bias_job_definition.go
  apis/v1alpha1/model_explainability_job_definition.go
  apis/v1alpha1/model_quality_job_definition.go
  apis/v1alpha1/monitoring_schedule.go
  apis/v1alpha1/processing_job.go
  apis/v1alpha1/training_job.go
  apis/v1alpha1/transform_job.go
  config/crd/bases/sagemaker.services.k8s.aws_dataqualityjobdefinitions.yaml
  config/crd/bases/sagemaker.services.k8s.aws_endpointconfigs.yaml
  config/crd/bases/sagemaker.services.k8s.aws_endpoints.yaml
  config/crd/bases/sagemaker.services.k8s.aws_hyperparametertuningjobs.yaml
  config/crd/bases/sagemaker.services.k8s.aws_modelbiasjobdefinitions.yaml
  config/crd/bases/sagemaker.services.k8s.aws_modelexplainabilityjobdefinitions.yaml
  config/crd/bases/sagemaker.services.k8s.aws_modelqualityjobdefinitions.yaml
  config/crd/bases/sagemaker.services.k8s.aws_models.yaml
  config/crd/bases/sagemaker.services.k8s.aws_monitoringschedules.yaml
  config/crd/bases/sagemaker.services.k8s.aws_processingjobs.yaml
  config/crd/bases/sagemaker.services.k8s.aws_trainingjobs.yaml
  config/crd/bases/sagemaker.services.k8s.aws_transformjobs.yaml
  generator.yaml
  go.mod
  go.sum
  pkg/resource/data_quality_job_definition/manager.go
  pkg/resource/data_quality_job_definition/sdk.go
  pkg/resource/endpoint/manager.go
  pkg/resource/endpoint/sdk.go
  pkg/resource/endpoint_config/manager.go
  pkg/resource/endpoint_config/sdk.go
  pkg/resource/hyper_parameter_tuning_job/manager.go
  pkg/resource/hyper_parameter_tuning_job/sdk.go
  pkg/resource/model/manager.go
  pkg/resource/model/sdk.go
  pkg/resource/model_bias_job_definition/manager.go
  pkg/resource/model_bias_job_definition/sdk.go
  pkg/resource/model_explainability_job_definition/manager.go
  pkg/resource/model_explainability_job_definition/sdk.go
  pkg/resource/model_quality_job_definition/manager.go
  pkg/resource/model_quality_job_definition/sdk.go
  pkg/resource/monitoring_schedule/manager.go
  pkg/resource/monitoring_schedule/sdk.go
  pkg/resource/processing_job/manager.go
  pkg/resource/processing_job/sdk.go
  pkg/resource/training_job/manager.go
  pkg/resource/training_job/sdk.go
  pkg/resource/transform_job/manager.go
  pkg/resource/transform_job/sdk.go
  templates/monitoring_schedule/sdk_delete_pre_build_request.go.tpl
  templates/monitoring_schedule/sdk_update_pre_build_request.go.tpl
Labels: approved
