Repository aws-controllers-k8s/sagemaker-controller, pull requests merged in 2022-12, with the labels that each got.

#174 Initial pipeline-execution resource
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/enums.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/pipeline_execution.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/sagemaker.services.k8s.aws_pipelineexecutions.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  go.sum
  helm/crds/sagemaker.services.k8s.aws_pipelineexecutions.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  pkg/resource/pipeline_execution/delta.go
  pkg/resource/pipeline_execution/descriptor.go
  pkg/resource/pipeline_execution/hooks.go
  pkg/resource/pipeline_execution/identifiers.go
  pkg/resource/pipeline_execution/manager.go
  pkg/resource/pipeline_execution/manager_factory.go
  pkg/resource/pipeline_execution/references.go
  pkg/resource/pipeline_execution/resource.go
  pkg/resource/pipeline_execution/sdk.go
  pkg/testutil/test_suite_runner.go
  templates/pipeline_execution/sdk_delete_pre_build_request.go.tpl
  test/e2e/__init__.py
  test/e2e/common/config.py
  test/e2e/resources/pipeline_execution.yaml
  test/e2e/resources/pipeline_processing.yaml
  test/e2e/tests/test_pipeline_execution.py
Labels: approved

#182 check in status for lastModifiedTime pipelineResources
  test/e2e/tests/test_pipeline.py
  test/e2e/tests/test_pipeline_execution.py
Labels: approved, lgtm

#181 Pipeline unit tests
  pkg/resource/pipeline/manager_test_suite_test.go
  pkg/resource/pipeline/testdata/sdkapi/create/create_success.json
  pkg/resource/pipeline/testdata/sdkapi/describe/describe_success.json
  pkg/resource/pipeline/testdata/test_suite.yaml
  pkg/resource/pipeline/testdata/v1alpha1/create/desired/invalid_before_create.yaml
  pkg/resource/pipeline/testdata/v1alpha1/create/desired/success_before_create.yaml
  pkg/resource/pipeline/testdata/v1alpha1/create/observed/invalid_create_attempted.yaml
  pkg/resource/pipeline/testdata/v1alpha1/create/observed/success_after_create.yaml
  pkg/resource/pipeline/testdata/v1alpha1/delete/observed/error_on_delete.yaml
  pkg/resource/pipeline/testdata/v1alpha1/delete/observed/not_found_on_delete.yaml
  pkg/resource/pipeline/testdata/v1alpha1/readone/desired/error_conditions_true.yaml
  pkg/resource/pipeline/testdata/v1alpha1/readone/desired/missing_required_field.yaml
  pkg/resource/pipeline/testdata/v1alpha1/readone/observed/conditions_clear_on_success.yaml
  pkg/resource/pipeline/testdata/v1alpha1/readone/observed/created.yaml
  pkg/resource/pipeline/testdata/v1alpha1/readone/observed/error_on_describe.yaml
  pkg/resource/pipeline/testdata/v1alpha1/update/desired/updated.yaml
  pkg/resource/pipeline/testdata/v1alpha1/update/observed/update_pipeline.yaml
Labels: approved

#183 Pipeline-Execution Unit Tests
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/pipeline_execution/manager_test_suite_test.go
  pkg/resource/pipeline_execution/testdata/sdkapi/create/create_success.json
  pkg/resource/pipeline_execution/testdata/sdkapi/describe/describe_executing.json
  pkg/resource/pipeline_execution/testdata/sdkapi/describe/describe_stopping.json
  pkg/resource/pipeline_execution/testdata/sdkapi/describe/describe_succeeded.json
  pkg/resource/pipeline_execution/testdata/test_suite.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/create/desired/invalid_before_create.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/create/desired/success_before_create.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/create/observed/invalid_create_attempted.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/create/observed/success_after_create.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/delete/observed/error_on_delete.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/delete/observed/not_found_on_delete.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/desired/error_conditions_true.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/desired/invalid.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/desired/missing_required_field.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/desired/stopping.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/observed/conditions_clear_on_success.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/observed/created.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/observed/error_on_describe.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/observed/stopping.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/readone/observed/succeeded.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/update/desired/update_pipeline_execution.yaml
  pkg/resource/pipeline_execution/testdata/v1alpha1/update/observed/updated_pipeline_execution.yaml
Labels: approved

#184 Fix: generator.yaml indent
  apis/v1alpha1/ack-generate-metadata.yaml
  generator.yaml
Labels: ok-to-test, approved, lgtm

#185 release artifacts for release v0.5.0
  apis/v1alpha1/ack-generate-metadata.yaml
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: ok-to-test, approved, lgtm

#186 Update to ACK runtime v0.21.0, code-generator v0.21.0
  apis/v1alpha1/ack-generate-metadata.yaml
  go.mod
  go.sum
  pkg/resource/app/tags.go
  pkg/resource/data_quality_job_definition/tags.go
  pkg/resource/domain/tags.go
  pkg/resource/endpoint/tags.go
  pkg/resource/endpoint_config/tags.go
  pkg/resource/feature_group/tags.go
  pkg/resource/hyper_parameter_tuning_job/tags.go
  pkg/resource/model/tags.go
  pkg/resource/model_bias_job_definition/tags.go
  pkg/resource/model_explainability_job_definition/tags.go
  pkg/resource/model_package_group/tags.go
  pkg/resource/model_quality_job_definition/tags.go
  pkg/resource/monitoring_schedule/tags.go
  pkg/resource/notebook_instance/tags.go
  pkg/resource/pipeline/tags.go
  pkg/resource/processing_job/tags.go
  pkg/resource/training_job/tags.go
  pkg/resource/transform_job/tags.go
  pkg/resource/user_profile/tags.go
Labels: approved, lgtm
